config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from core.dashboard.views import DashboardTemplateView

urlpatterns = [
    path('', include('core.login.urls')),
    path('admin/', admin.site.urls),
    path('core/', include('core.pos.urls')),
    path('accounts/', include('core.accounts.urls')),
    path('reports/', include('core.reports.urls')),
    path('dashboard/', DashboardTemplateView.as_view(), name='dashboard'),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/accounts/urls.py
from django.urls import path

from core.accounts.views.user.views import *

app_name = 'accounts'

urlpatterns = [
    path('', UserTemplateView.as_view(), name='user_list'),
    path('create/', UserCreateView.as_view(), name='user_create'),
    path('update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),
    path('my/profile/', UserProfileView.as_view(), name='user_profile'),
    path('update/password/', UserChangePassswordView.as_view(), name='user_update_password'),
    path('change/group/<int:pk>/', UserChangeGroupView.as_view(), name='user_change_group'),
]

core/pos/urls.py
from django.urls import path

from core.pos.views.category.views import *
from core.pos.views.company.views import CompanyUpdateView
from core.pos.views.customer.views import *
from core.pos.views.log.views import LogTemplateView
from core.pos.views.product.views import *
from core.pos.views.sale.views import *

app_name = 'pos'

urlpatterns = [
    # ! Category
    path('category/', CategoryTemplateView.as_view(), name='category_list'),
    path('category/create/', CategoryCreateView.as_view(), name='category_create'),
    path('category/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('category/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    # ! Product
    path('product/', ProductTemplateView.as_view(), name='product_list'),
    path('product/create/', ProductCreateView.as_view(), name='product_create'),
    path('product/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    # ! Customer
    path('customer/', CustomerTemplateView.as_view(), name='customer_list'),
    path('customer/create/', CustomerCreateView.as_view(), name='customer_create'),
    path('customer/update/<int:pk>/', CustomerUpdateView.as_view(), name='customer_update'),
    path('customer/delete/<int:pk>/', CustomerDeleteView.as_view(), name='customer_delete'),
    # ! SALE
    path('sale/', SaleTemplateView.as_view(), name='sale_list'),
    path('sale/create/', SaleCreateView.as_view(), name='sale_create'),
    path('sale/delete/<int:pk>/', SaleDeleteView.as_view(), name='sale_delete'),
    path('sale/invoice/pdf/<int:pk>/', SaleInvoicePdfView.as_view(), name='sale_invoice_pdf'),
    # ! LOG
    path('log/', LogTemplateView.as_view(), name='log_list'),
    # ! Company
    path('company/', CompanyUpdateView.as_view(), name='company_update'),

]

core/reports/urls.py
from django.urls import path

from core.reports.views.sale.views import ReportSaleTemplateView

app_name = 'reports'

urlpatterns = [
    path('sale/', ReportSaleTemplateView.as_view(), name='sale_report'),

]

core/reports/forms.py
from django import forms


class ReportSaleForm(forms.Form):
    date_range = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Ingrese el rango de fecha para el filtrado.',
    }), label='Rango de Fecha')

core/reports/views/sale/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import FormView

from core.pos.mixins import ValidatePermissionRequiredMixin
from core.pos.models import Sale
from core.reports.forms import ReportSaleForm

MODULE_NAME = 'Venta'


class ReportSaleTemplateView(LoginRequiredMixin, ValidatePermissionRequiredMixin, FormView):
    form_class = ReportSaleForm
    permission_required = 'view_sale'
    template_name = 'sale/report.html'

    def post(self, request, *args, **kwargs):
        data = {}
        try:
            action = request.POST['action']
            if action == 'get_sales':
                start_date = request.POST['start_date']
                end_date = request.POST['end_date']
                sales = Sale.objects.all()
                if len(start_date) and len(end_date):
                    sales = sales.filter(date_joined__range=[start_date, end_date])
                data = [sale.toJSON() | {'position': position} for position, sale in enumerate(sales, start=1)]
            else:
                data['error'] = 'No ha ingresado ninguna opción.'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super(ReportSaleTemplateView, self).get_context_data(**kwargs)
        context['title'] = 'Reporte de Venta'
        context['entity'] = MODULE_NAME
        context['list_url'] = reverse_lazy('dashboard')
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="author" content="Marin Tantalean, Moises Fernando">
    <title>{{ title }}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'img/logotipo.png' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.2.0/css/adminlte.min.css' %}">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.2.0/plugins/jquery/jquery.min.js' %}"></script>
    <!-- SweetAlert2 -->
    <script src="{% static 'lib/sweetalert2-11.0.16/js/sweetalert2.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/sweetalert2-11.0.16/css/sweetalert2.min.css' %}">
    <!-- Jquery-Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-3.3.4/css/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-3.3.4/js/jquery-confirm.min.js' %}"></script>
    <!--jquery-loading-overlay-->
    <script src="{% static 'lib/jquery-loading-overlay-2.1.7/js/loadingoverlay.min.js' %}"></script>
    {% block head %}{% endblock %}
    <!-- Mis funciones -->
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>
</head>
<body>

</body>
</html>
<body class="hold-transition sidebar-mini layout-fixed">
<!-- Site wrapper -->
<div class="wrapper">
    <!-- Navbar -->
    {% include 'header.html' %}
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    {% include 'sidebar.html' %}

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper" >
        {% block body %}{% endblock %}
    </div>
    <!-- /.content-wrapper -->

    {% include 'footer.html' %}

</div>
<!-- ./wrapper -->

{% block modals %}{% endblock %}

{% block javascript %}{% endblock %}

{% if messages %}
    <script type="application/javascript">
        let errors = '';
        {% for message in messages %}
            errors += '{{ message }}\n';
        {% endfor %}
        get_errors(errors);
    </script>
{% endif %}
<!-- Bootstrap 4 -->
<script src="{% static 'lib/adminlte-3.2.0/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'lib/adminlte-3.2.0/js/adminlte.min.js' %}"></script>

</body>
</html>

templates/body.html
{% extends 'base.html' %}

{% block body %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{% url 'dashboard' %}">Home</a></li>
                        <li class="breadcrumb-item active">{{ entity }}</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        {% block content %}{% endblock %}
    </section>
    <!-- /.content -->
{% endblock %}

templates/delete.html
{% extends 'body.html' %}

{% block content %}
    <div class="container-fluid">
        <form action="." method="post" data-url="{{ list_url }}">
            <div class="row">
                <div class="col-12">
                    <!-- Default box -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title"><i class="fas fa-trash"></i> {{ title }}</h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="{{ action }}">
                            <h5><span class="badge badge-warning">{{ object }}</span></h5>
                            <p>Estás a punto de eliminar este registro. Esta acción es irreversible y
                                la información asociada se perderá permanentemente.</p>
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button class="btn btn-success btn-sm" type="submit"><i class="fas fa-trash"></i> Eliminar Registro</button>
                            <a class="btn btn-danger btn-sm" href="{{ list_url }}"><i class="fas fa-times"></i> Cancelar</a>
                        </div>
                        <!-- /.card-footer-->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('form').on('submit', function (evt) {
                evt.preventDefault();
                let params = new FormData(this);
                let data_url = $(this).attr('data-url');
                set_data_server({
                    'content': '¿Estas seguro que deseass eliminar el siguiente registro?',
                    'params': params,
                    'callback': function () {
                        get_sweetalert2({
                            'html': 'Se elimino correctamente el registro.',
                            'callback': function () {
                                location.href = data_url;
                            }
                        })
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/footer.html
<footer class="main-footer">
    <div class="float-right d-none d-sm-block">
        <b>Version</b> 2.0.0
    </div>
    <strong>Copyright &copy; 2023-2024 <a href='https://wa.link/xhxfh6' target='_blanks'>Marin Tantalean, Moises Fernando</a>.</strong> All rights reserved.
</footer>

templates/form.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    {% block head_form %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form action="." method="post" data-url="{{ list_url }}">
            <div class="row">
                <div class="col-12">
                    <!-- Default box -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">
                                {% if action == 'create' %}
                                    <i class="fas fa-plus"></i>
                                {% else %}
                                    <i class="fas fa-edit"></i>
                                {% endif %}
                                {{ title }}
                            </h3>
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <input type="hidden" name="action" value="{{ action }}">

                            {% for field in form %}
                                <div class="form-group">
                                    <label>{{ field.label }}</label>
                                    <div class="input-group  mb-3">
                                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                                        {% block additional_button %}{% endblock %}
                                    </div>
                                </div>

                            {% endfor %}

                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer">
                            <button class="btn btn-success btn-sm" type="submit"><i class="fas fa-save"></i> Guardar Registro</button>
                            <a class="btn btn-danger btn-sm" href="{{ list_url }}"><i class="fas fa-times"></i> Cancelar</a>
                        </div>
                        <!-- /.card-footer-->
                    </div>
                    <!-- /.card -->
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('form').on('submit', function (evt) {
                evt.preventDefault();
                let params = new FormData(this);
                let data_url = $(this).attr('data-url');
                set_data_server({
                    'params': params,
                    'callback': function (response) {
                        get_sweetalert2({
                            'html': 'Se realizo correctamente la acción.',
                            'callback': function () {
                                location.href = data_url;
                            }
                        });
                    }
                });
            });
        });
    </script>
{% endblock %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <div class="dropdown">
                <a class="btn {% if request.user.groups.all.count > 1 %}dropdown-toggle{% endif %}" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    {{ request.session.group.names }}
                </a>
                {% if request.user.groups.all.count > 1 %}
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

                        {% for group in request.user.groups.all %}
                            {% if group.id != request.session.group.id %}
                                <a class="dropdown-item" href="{% url 'accounts:user_change_group' group.id %}">{{ group }}</a>
                            {% endif %}
                        {% endfor %}

                    </div>
                {% endif %}
            </div>
        </li>

        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-ellipsis-v"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <a href="{% url 'accounts:user_profile' %}" class="dropdown-item">
                    <i class="fas fa-user-edit mr-2"></i> Actualizar Perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="{% url 'accounts:user_update_password' %}" class="dropdown-item">
                    <i class="fas fa-key mr-2"></i> Actualizar contraseña
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <b>Última fecha de conexión:</b><br>
                    {{ request.user.last_login }}</a>
            </div>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off"></i>
            </a>
        </li>
    </ul>
</nav>

templates/list.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <!-- Datatables -->
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/css/dataTables.bootstrap5.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/css/responsive.bootstrap5.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.25/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/js/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/responsive.bootstrap5.min.js' %}"></script>
    {% block head_list %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fas fa-search"></i> {{ title }}</h3>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover p-0" id="data">
                                <thead>
                                {% block cols %}{% endblock %}
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        {% block buttons_list %}
                            <a class="btn btn-primary btn-sm" href="{{ create_url }}"><i class="fas fa-plus"></i> Nuevo Registro</a>
                            <a class="btn btn-success btn-sm" href="{{ list_url }}"><i class="fas fa-sync-alt"></i> Actualizar</a>
                        {% endblock %}
                    </div>
                    <!-- /.card-footer-->
                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
{% endblock %}

templates/panel.html
{% extends 'body.html' %}
{% load static %}

{% block head %}
    <script src="{% static 'lib/highcharts-9.1.1/highcharts.js' %}"></script>
    <script src="{% static 'js/panel/panel.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
            <div class="table-responsive">
                <div class="card">
                    <h4 class="font-weight-bold text-center mb-3">
                        <i class="fas fa-shopping-cart"></i> Las 5 últimas ventas realizadas
                    </h4>
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th scope="col" style="width: 10%;">F. Venta</th>
                            <th scope="col" style="width: 10%;">Factura</th>
                            <th scope="col" style="width: 20%;">Cliente</th>
                            <th scope="col" style="width: 5%;">Subtotal</th>
                            <th scope="col" style="width: 5%;">Iva</th>
                            <th scope="col" style="width: 5%;">Total</th>
                        </tr>
                        </thead>

                        <tbody>
                        {% for sale in sales %}
                            <tr>
                                <td>{{ sale.date_joined }}</td>
                                <td>{{ sale.generate_code_sale }}</td>
                                <td>{{ sale.customer.get_full_names }}</td>
                                <td>S/.{{ sale.subtotal }}</td>
                                <td>{{ sale.iva }}</td>
                                <td>S/.{{ sale.total }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-6">
            <div class="card">
                <div id="container-donut"></div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card">
                <div id="container-bar"></div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascript %}
{% endblock %}

templates/report.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}
    <!-- Datatables -->
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/css/dataTables.bootstrap5.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/css/responsive.bootstrap5.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.25/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/js/dataTables.bootstrap5.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/responsive-2.2.9/js/responsive.bootstrap5.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.25/plugins/buttons-1.7.1/css/buttons.bootstrap.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.25/plugins/buttons-1.7.1/js/dataTables.buttons.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/jszip-2.5.0/jszip.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/pdfmake-0.1.36/pdfmake.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/pdfmake-0.1.36/vfs_fonts.js' %}" type="text/javascript"></script>
    <script src="{% static 'lib/datatables-1.10.25/plugins/buttons-1.7.1/js/buttons.html5.min.js' %}" type="text/javascript"></script>
    <!-- DateRangerPicker -->
    <script src="{% static 'lib/moment-2.25.3/moment.js' %}" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'lib/bootstrap-daterangepicker-3.1/js/daterangepicker.js' %}"></script>
    <script type="text/javascript" src="{% static 'lib/bootstrap-daterangepicker-3.1/js/spanish.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'lib/bootstrap-daterangepicker-3.1/css/daterangepicker.css' %}"/>
    {% block head_report %}{% endblock %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <!-- Default box -->
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title"><i class="fas fa-search"></i> {{ title }}</h3>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-4">
                                <div class="form-group">
                                    <label>{{ form.date_range.label }}</label>
                                    <div class="input-group">
                                        {{ form.date_range|add_class:'form-control'|attr:'autocomplete:off' }}
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" id="btnShowAll"><i class="fas fa-search"></i> Mostar Todos</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover p-0" id="data">
                                <thead>
                                {% block cols %}{% endblock %}
                                </thead>
                                <tbody></tbody>
                            </table>
                        </div>
                    </div>

                </div>
                <!-- /.card -->
            </div>
        </div>
    </div>
{% endblock %}

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
        <img src="{% static 'img/logotipo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">POS-STORE</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_imagen }}" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="{% url 'accounts:user_profile' %}" class="d-block">{{ request.user.first_name }}</a>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-boxes"></i>
                        <p>
                            Mi Bodega
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'pos:category_list' %}" class="nav-link">
                                <i class="fas fa-truck-loading nav-icon"></i>
                                <p>Categoria</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'pos:product_list' %}" class="nav-link">
                                <i class="fas fa-box nav-icon"></i>
                                <p>Producto</p>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-cart-plus"></i>
                        <p>
                            Facturación
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'pos:customer_list' %}" class="nav-link">
                                <i class="fas fa-user-friends nav-icon"></i>
                                <p>Cliente</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'pos:sale_list' %}" class="nav-link">
                                <i class="fas fa-shopping-cart nav-icon"></i>
                                <p>Venta</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-chart-line"></i>
                        <p>
                            Reportes
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'reports:sale_report' %}" class="nav-link">
                                <i class="fas fa-shopping-cart nav-icon"></i>
                                <p>Venta</p>
                            </a>
                        </li>
                    </ul>
                </li>


                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-lock"></i>
                        <p>
                            Seguridad
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'accounts:user_list' %}" class="nav-link">
                                <i class="fas fa-user nav-icon"></i>
                                <p>Usuario</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'pos:log_list' %}" class="nav-link">
                                <i class="fas fa-binoculars nav-icon"></i>
                                <p>Bitácora</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-wrench"></i>
                        <p>
                            Configuración
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{% url 'pos:company_update' %}" class="nav-link">
                                <i class="fas fa-building nav-icon"></i>
                                <p>Compañia</p>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>